joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joints_positions_controller:
  type: my_pid_6dof/MyPid6Dof
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  joint_1_control_params:
    pid:
      p: 200.0
      i: 2.0
      d: 20.0
      
  joint_2_control_params:
    pid:
      p: 350.0
      i: 5.0
      d: 45.0

  joint_3_control_params:
    pid:
      p: 200.0
      i: 1.0
      d: 10.0

  joint_4_control_params:
    pid:
      p: 70.0
      i: 1.0
      d: 1.0

  joint_5_control_params:
    pid:
      p: 50.0
      i: 0.5
      d: 0.5

  joint_6_control_params:
    pid:
      p: 30.0
      i: 0.3
      d: 0.5
