# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: pendulum
  joint_model_group_pose: zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: pendulum_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
pendulum_controller:
  type: par_computado_1dof/ParComputado1Dof
  joint: joint_1

  joint_1_control_params:
    pid:
      p: 200.0
      i: 2.0
      d: 20.0
    model_params:
      I: 0.2
      b: 1.0
      c: 0.0