# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
arm_group_controller:
  type: par_computado_6dof/ParComputado6Dof
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  joint_1_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0
      
  joint_2_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0

  joint_3_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0

  joint_4_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0

  joint_5_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0

  joint_6_control_params:
    pid:
      p: 625.0
      i: 0.0
      d: 50.0